# Generated by Django 5.1.2 on 2024-11-25 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(default='')),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
                ('contenuCrypte', models.TextField(default='')),
                ('cle', models.TextField(default='')),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_envoye', to=settings.AUTH_USER_MODEL)),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dateEnvoi'],
            },
        ),
    ]
